Update build-openwrt.yml

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -74,7 +74,13 @@ jobs:
       - name: Load custom configuration
         run: |
           cd openwrt
-          [ -f $GITHUB_WORKSPACE/$CONFIG_FILE ] && mv $GITHUB_WORKSPACE/$CONFIG_FILE .config
+          if [ -f $GITHUB_WORKSPACE/$CONFIG_FILE ]; then
+            mv $GITHUB_WORKSPACE/$CONFIG_FILE .config
+            echo "Custom .config loaded successfully."
+          else
+            echo "Error: Custom .config not found at $GITHUB_WORKSPACE/$CONFIG_FILE"
+            exit 1
+          fi
           make defconfig
 
       - name: Download package source
